### ISSUE TITLE
How to send mail

### ISSUE THREAD

**Issue by hyahm** [foxcpp/maddy#191]
I send mail in local with python
```python
#!/usr/bin/python3
 
import smtplib
from email.mime.text import MIMEText
from email.header import Header
 
# 第三方 SMTP 服务
mail_host="smtp.hyahm.com"  #设置服务器
mail_user="cander@hyahm.com"    #用户名
mail_pass="12345678"   #口令 
 
 
sender = 'cander@hyahm.com'
receivers = ['727023460@qq.com']  # 接收邮件，可设置为你的QQ邮箱或者其他邮箱
 
message = MIMEText('我这边看不到你发给我的信息， 只能看到我发给你的', 'plain', 'utf-8')
message['From'] = Header("菜鸟教程")
message['To'] =  Header("测试")
 
subject = '我这边看不到你发给我的信息'
message['Subject'] = Header(subject)
 
 
try:
    smtpObj = smtplib.SMTP() 
    # smtpObj = smtplib.SMTP_SSL(mail_host, 587)
    smtpObj.connect(mail_host, 25)    # 25 为 SMTP 端口号
    # smtpObj.helo()
    # smtpObj.starttls()
    smtpObj.login(mail_user,mail_pass)
    smtpObj.sendmail(sender, receivers, message.as_string())
    print ("邮件发送成功")
except smtplib.SMTPException as e:
    print(e)
    print ("Error: 无法发送邮件")
```
> error message
```
SMTP AUTH extension not supported by server.
Error: 无法发送邮件

```

 
# start server
```shell
[root@storebak maddy]# go run main.go 
alias_file: ignoring non-existent file: /etc/maddy/aliases	
smtp: listening on tcp://0.0.0.0:25	
sign_dkim: generating a new rsa2048 keypair...	
sign_dkim: generated a new rsa2048 keypair, private key is in dkim_keys/example.org_default.key, TXT record with public key is in dkim_keys/example.org_default.dns,
put its contents into TXT record for default._domainkey.example.org to make signing and verification work	
alias_file: ignoring non-existent file: /etc/maddy/aliases	
submission: listening on tls://0.0.0.0:465	
submission: listening on tcp://0.0.0.0:587	
imap: listening on tls://0.0.0.0:993	
imap: listening on tcp://0.0.0.0:143	

```
# And I had create a user
```shell
[root@storebak maddyctl]# go run main.go users create cander@hyahm.com
Enter password for new user:
```

**Comment by foxcpp** [comment]
maddy permits sending of outbound messages only on Submission port and only with TLS negotiated (between client and server). That's port 587 and uncomment the starttls line.

Also, in maddy.conf, both hostname and local_domains (or primary_domain) should be set to appropriate values. That's smtp.hyahm.com and hyahm.com, judging from your code.

**Comment by hyahm** [comment]
```
[root@storebak ~]# cat /etc/maddy/maddy.conf 
# hostname is the identifier of this mail server.
# It is recommended to set it to the domain that resolves to the IP of this
# server.
$(hostname) = hyahm.com

# Primary domain is used as a sender of autogenerated messages and
# ADMD for DKIM signatures.
# For simple configurations, it is usually equal to $(hostname).
$(primary_domain) = hyahm.com

# All domains we want to receive messages for.
$(local_domains) = $(primary_domain)

```

**Comment by hyahm** [comment]
port 587 is open

> config
```
[root@storebak ~]# cat /etc/maddy/maddy.conf 
# hostname is the identifier of this mail server.
# It is recommended to set it to the domain that resolves to the IP of this
# server.
$(hostname) = smtp.hyahm.com

# Primary domain is used as a sender of autogenerated messages and
# ADMD for DKIM signatures.
# For simple configurations, it is usually equal to $(hostname).
$(primary_domain) = hyahm.com

# All domains we want to receive messages for.
$(local_domains) = $(primary_domain)

```
```python
#!/usr/bin/python3
 
import smtplib
from email.mime.text import MIMEText
from email.header import Header
 
# 第三方 SMTP 服务
mail_host="smtp.hyahm.com"  #设置服务器
mail_user="cander@hyahm.com"    #用户名
mail_pass="12345678"   #口令 
 
 
sender = 'cander@hyahm.com'
receivers = ['727023460@qq.com']  # 接收邮件，可设置为你的QQ邮箱或者其他邮箱
 
message = MIMEText('我这边看不到你发给我的信息， 只能看到我发给你的', 'plain', 'utf-8')
message['From'] = Header("菜鸟教程")
message['To'] =  Header("测试")
 
subject = '我这边看不到你发给我的信息'
message['Subject'] = Header(subject)
 
 
try:
    # smtpObj = smtplib.SMTP() 
    smtpObj = smtplib.SMTP_SSL(mail_host, 587)
    # smtpObj.connect(mail_host, 25)    # 25 为 SMTP 端口号
    # smtpObj.helo()
    smtpObj.starttls()
    smtpObj.login(mail_user,mail_pass)
    smtpObj.sendmail(sender, receivers, message.as_string())
    print ("邮件发送成功")
except smtplib.SMTPException as e:
    print(e)
    print ("Error: 无法发送邮件")
```

```error msg
[root@cander test]# python3 testemail.py 
Traceback (most recent call last):
  File "testemail.py", line 26, in <module>
    smtpObj = smtplib.SMTP_SSL(mail_host, 587)
  File "/usr/lib64/python3.7/smtplib.py", line 1031, in __init__
    source_address)
  File "/usr/lib64/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.7/smtplib.py", line 1039, in _get_socket
    server_hostname=self._host)
  File "/usr/lib64/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)
```

**Comment by hyahm** [comment]
I have change port to 465
```python
#!/usr/bin/python3
 
import smtplib
from email.mime.text import MIMEText
from email.header import Header
 
# 第三方 SMTP 服务
mail_host="smtp.hyahm.com"  #设置服务器
mail_user="cander@hyahm.com"    #用户名
mail_pass="12345678"   #口令 
 
 
sender = 'cander@hyahm.com'
receivers = ['727023460@qq.com']  # 接收邮件，可设置为你的QQ邮箱或者其他邮箱
 
message = MIMEText('我这边看不到你发给我的信息， 只能看到我发给你的', 'plain', 'utf-8')
message['From'] = Header("菜鸟教程")
message['To'] =  Header("测试")
 
subject = '我这边看不到你发给我的信息'
message['Subject'] = Header(subject)
 
 
try:
    # smtpObj = smtplib.SMTP() 
    smtpObj = smtplib.SMTP_SSL(mail_host, 465)
    # smtpObj.connect(mail_host, 25)    # 25 为 SMTP 端口号
    # smtpObj.helo()
    # smtpObj.starttls()
    smtpObj.login(mail_user,mail_pass)
    smtpObj.sendmail(sender, receivers, message.as_string())
    print ("邮件发送成功")
except smtplib.SMTPException as e:
    print(e)
    print ("Error: 无法发送邮件")
```

error message
```
(554, b'5.6.0 Invalid address in To (msg ID = 65dfb16d)')
Error: 无法发送邮件
```

> server message
```
imap: listening on tcp://0.0.0.0:143	
submission: incoming message	{"msg_id":"65dfb16d","sender":"cander@hyahm.com","src_host":"[172.31.38.100]","src_ip":"127.0.0.1:48542","username":"cander@hyahm.com"}
submission: RCPT ok	{"msg_id":"65dfb16d","rcpt":"727023460@qq.com"}
submission: adding missing Message-ID	
submission: DATA error	{"addr":"=?utf-8?b?5rWL6K+V?=","modifier":"submission_prepare","msg_id":"65dfb16d","reason":"mail: missing '@' or angle-addr","smtp_code":554,"smtp_enchcode":"5.6.0","smtp_msg":"Invalid address in To"}
submission: aborted	{"msg_id":"65dfb16d"}


```

**Comment by hyahm** [comment]
I have solved ,  thanks
```
message['From'] = Header("菜鸟教程")
message['To'] =  Header("测试")
```
change to
```
message['From'] = Header(sender)
message['To'] =  Header(receivers[0])
 
```

**Comment by eurake** [comment]
@hyahm  通过你指引， maddy 后台现接收邮件与发送邮件都正常，但存在以下2点， 1不能正常通过邮件工具登录，2 发送给QQ 163 的邮件不能接收， 显示 stmp code 450

**Comment by hyahm** [comment]
看看你哪里配置有问题，  工具测试过都是可以登录使用的
